### ISSUE TITLE
Allow for custom handlebars helpers

### ISSUE THREAD

**Issue by diegofcornejo** [satelite-digital/engineer#6]
**Is your feature request related to a problem? Please describe.**
While it's great that engineer implements handlebars as a template engine, I would like to be able to add custom helpers to it to enhance functionality.

**Describe the solution you'd like**
The configuration object could allow an options key which would expect an options object including a custom handlebars instance that would be used instead of the built-in one.

**Comment by ErickRuano** [comment]
Thank you for the suggestion, I just merged some changes that implement this feature.  If you are using engineer as a library please update to 3.3.2 or if you are using the CLI please upgrade to 1.1.1.

You'll find instructions on how to use the new feature here:
https://github.com/satelite-digital/engineer#options

If you have any doubts or further requests please contact or open a new issue.
